### PR TITLE
Remove dependency on hawk, upgrade request

### LINKED ISSUE #346: security vulnerability? due to old hawk@3.1.3 (and hoek@2.16.3) dependency
in our project, snyk recently started complaining that we have a dependency with a known security vulnerability. It complains about `hoek@2.16.3` which is required by `hawk@3.1.3` which is required by the latest version of `node-pre-gyp`

the latest version of `hoek` (version 5.0.3) fixed the vulnerability. But `node-pre-gyp` has locked the version of `hawk` to 3.1.3 while the latest version of `hawk` is 7.0.7. Using such an old version of `hawk` also uses a very old version of `hoek`.

Would it be easy to upgrade to the latest version of `hawk` so we get the latest version of `hoek` without the vulnerability?

More info about the (low prio) vulnerability in `hoek` can be found at https://snyk.io/vuln/npm:hoek:20180212

### PR DESCRIPTION
**Pull request by krotscheck**
This patch removes the explicit dependency on hawk, and upgrades request
to the newest version. It also removes node 0.10 from the testing grid,
as this version has been EOL'd by the node foundation, and doesn't support
es6 syntax used in the newer introduced dependencies.

https://nodesecurity.io/advisories/566
https://hackerone.com/reports/310439
https://github.com/nodejs/Release

Closes #346

### CODE REVIEW

**Comment by krotscheck** [comment]
The only mention of hawk appears to be the package.json file:
https://github.com/mapbox/node-pre-gyp/search?utf8=%E2%9C%93&q=hawk&type=

**Comment by SebastianSchmidt** [comment]
The package [request@2.81.0](https://github.com/mapbox/node-pre-gyp/blob/master/package.json#L27) depends on `hawk@3.1.3`.
This pull request does not completely remove the dependency on hawk and does not solve #346.

Updating to `request@2.83.0` fixes the vulnerability.
`request@2.83.0` uses `hawk@6.0.2` which depends on `hoek@4.2.1` (Fixed vulnerability: hapijs/hoek#230).

**Comment by krotscheck** [comment]
@SebastianSchmidt Done. Jetzt auf Travis warten ⏳

**Comment by SebastianSchmidt** [comment]
`request@2.83.0` and Node 0.10: #320, #342

**Comment by krotscheck** [comment]
Yeah, saw that. Given that node 0.10 is EOL, I removed it from the testing grid.

**Comment by krotscheck** [comment]
@springmeyer Any chance you can take a look at this?

**Comment by JulianLaval** [comment]
Would be great to have this PR merged in -- any updates? 🙂

**Comment by kontrollanten** [comment]
Any updates on this?

**Comment by Pablodotnet** [comment]
Any updates on this? We need the merge ASAP!

**Comment by nhodges** [comment]
Whoops, just saw this PR. I also made a PR to address this, #349. Many packages are waiting on this so it can go upstream.

**Comment by ronkorving** [comment]
Yeah, waiting too. Does node-pre-gyp only have a single maintainer?

**Comment by fenichelar** [comment]
Merging this PR and releasing a new version would be great! :)

**Comment by springmeyer** [comment]
Thanks for this PR. Sorry for the wait in review/merging. Will merge now and release as `v0.7.0.`

**Comment by springmeyer** [comment]
node-pre-gyp@0.7.0 is now published: https://www.npmjs.com/package/node-pre-gyp

**Pull request merged**
