### PR TITLE
Update rc to ^1.2.7 in package.json

### LINKED ISSUE #378: security vulnerability caused by rc@1.2.6
In our project, Snyk reported `rc@1.2.6` as a dependency with a known security vulnerability, because it depends on `deep-extend@0.4.2`.

The latest version of rc (1.2.7) fixed this vulnerability.

More info about the (low priority) vulnerability in `deep-extend@0.4.2` can be found at 
https://snyk.io/vuln/npm:deep-extend:20180409

### PR DESCRIPTION
**Pull request by paolo-tanium**
Upgrading rc to 1.2.7. This should fix #378

### CODE REVIEW

**Comment by brettz9** [comment]
Any ETA on this getting reviewed, merged, and released?

**Comment by merlinpatt** [comment]
There is now 1.2.8 for rc, so might as well update to that while this merge is waiting

**Comment by zhuangya** [comment]
> There is now 1.2.8 for rc, so might as well update to that while this merge is waiting

just change rc's version to `10.0.0`

**Comment by gustawdaniel** [comment]
I see that in `v0.10.0` of this pacage version of `rc` is `^1.1.7`. Taking into account this update of `rc`

https://github.com/dominictarr/rc/commit/73f285bb1f749331eaeab6c41f4505f90fe4ac35

to version `1.2.8` that updated version of `deep-extend` to `0.6.0` i propose to change version of

rc in this package to `1.2.8`.

```
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ deep-extend                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=0.5.1                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ bcrypt                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ bcrypt > node-pre-gyp > rc > deep-extend                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/612                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

**Pull request closed without merging**
