### PR TITLE
libc default is 'unknown' unless linux target

### PR DESCRIPTION
**Pull request by mark-buer**
For #383

### CODE REVIEW

**Comment by nicolasnoble** [comment]
So, I'm not sure about your suggestion, @mark-buer. If you are cross-compiling, you should know what to put as options when invoking `npm rebuild`. IMHO, I would rather have the user of the cross-compilation tool to pass the `--target_libc` option. For instance, even if you are defaulting to glibc because you are cross-compiling to alpine, you want to override this with `musl`, instead of `glibc` or `unknown`.

Sure, `node-pre-gyp` could have some sort of logic to default to `unknown` as you are suggesting in this PR, but it's kind of muddying the waters even further, and will create even more weird bugs in the case someone cross-compiles for Alpine for example.

My stance would be a tiny stricter than this to be honest: if cross compiling, (which I'm not sure how to detect this, but still), `node-pre-gyp` should refuse to work if all of the variables aren't set.

**Comment by mark-buer** [comment]
Fair enough. My fix was a knee-jerk reaction to my encountering a dependencies attempt to download a binary with "win32" _and_ "glibc" present in the same name!

> My stance would be a tiny stricter than this to be honest: if cross compiling, (which I'm not sure how to detect this, but still), node-pre-gyp should refuse to work if all of the variables aren't set.

I think I agree with the sentiment of your stance. One is either autodetecting everything and can specify/override nothing, or, one is cross compiling and must specify everything.

But I'd still argue that `--target_libc`, auto detected or not, makes no sense for some targets (such as win32 which was the original problem I was trying to solve). The ONLY acceptable target_libc option for win32 is unknown. The user shouldn't be able to specify an illegal combination of variables.

How about - if cross compiling, node-pre-gyp should refuse to work if all of the _relevant_ variables aren't set (for that family)?

**Comment by nicolasnoble** [comment]
Yeah, that's reasonable too. I'm still not sure how node-pre-gyp could detect cross compilation to be honest :-)

In all cases, if you look at https://github.com/electron-userland/electron-builder/issues/3049, I'm arguing that since electron-builder kinda knows about node-pre-gyp, it should also be responsible for setting this variable properly.

**Comment by springmeyer** [comment]
> I'm arguing that since electron-builder kinda knows about node-pre-gyp, it should also be responsible for setting this variable properly.

👍  hence going to close this. thanks all.

**Pull request closed without merging**
