### PR TITLE
Increase timeouts for HTTP requests

### PR DESCRIPTION
**Pull request by mapsam**
This adds the `open_timeout` and `request_timeout` options to needle's  GET requests in lib/install.js, which should reduce the number of "socket hung up" errors. 

These errors were previously "Completion callback never invoked" as noted in #367 but those appear to be fixed (at least made more explicit) by #377 

I don't have a great understanding of what a proper timeout setting should be, but these should be good to start with.

cc @springmeyer

### CODE REVIEW

**Comment by mapsam** [comment]
The timeout changes don't seem to be helping much, so I'm trying something new by passing in a customer http agent using the native `https` module and calculating how many sockets we should use based on the available cpus.. here's hoping!

**Comment by mapsam** [comment]
I added `NODE_DEBUG=http` to the test command (which doesn't seem to work on windows, but is giving us a bit more information. Haven't been able to recreate the socket hang up, but seeing `install error` more frequently.

<details>

<summary>Here's the debug stack with socket timeouts from s3</summary>

([travis build](https://travis-ci.org/mapbox/node-pre-gyp/jobs/392697532))

```
not ok 140 Error: Command failed 'V=1 npm install --clang=1 --fallback-to-build=false'
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      [Error: Command failed 'V=1 npm install --clang=1  --fallback-to-build=false']
    at: <anonymous> (/Users/travis/build/mapbox/node-pre-gyp/test/build.test.js:426:23)
    stack: |-
      HTTP 4117: call onSocket 0 0
      HTTP 4117: createConnection node-pre-gyp-tests.s3-us-west-1.amazonaws.com:443::::::::: { servername: 'node-pre-gyp-tests.s3-us-west-1.amazonaws.com',
        keepAliveMsecs: 60000,
        maxSockets: 32,
        keepAlive: true,
        _defaultAgent: 
         Agent {
           domain: null,
           _events: { free: [Function] },
           _eventsCount: 1,
           _maxListeners: undefined,
           defaultPort: 443,
           protocol: 'https:',
           options: { path: null },
           requests: {},
           sockets: {},
           freeSockets: {},
           keepAliveMsecs: 1000,
           keepAlive: false,
           maxSockets: Infinity,
           maxFreeSockets: 256,
           maxCachedSessions: 100,
           _sessionCache: { map: {}, list: [] } },
        agent: 
         Agent {
           domain: null,
           _events: { free: [Function] },
           _eventsCount: 1,
           _maxListeners: undefined,
           defaultPort: 443,
           protocol: 'https:',
           options: 
            { keepAliveMsecs: 60000,
              maxSockets: 32,
              keepAlive: true,
              path: null },
           requests: {},
           sockets: 
            { 'node-pre-gyp-tests.s3-us-west-1.amazonaws.com:443:::::::::': [] },
           freeSockets: {},
           keepAliveMsecs: 60000,
           keepAlive: true,
           maxSockets: 32,
           maxFreeSockets: 256,
           maxCachedSessions: 100,
           _sessionCache: { map: {}, list: [] } },
        protocol: 'https:',
        host: 'node-pre-gyp-tests.s3-us-west-1.amazonaws.com',
        port: 443,
        path: null,
        method: 'get',
        headers: 
         { accept: '*/*',
           'user-agent': 'node-pre-gyp (v0.10.1-pre, npm/5.6.0 node/v8.11.3 darwin x64)',
           host: 'node-pre-gyp-tests.s3-us-west-1.amazonaws.com' },
        _agentKey: 'node-pre-gyp-tests.s3-us-west-1.amazonaws.com:443:::::::::' }
      HTTP 4117: sockets node-pre-gyp-tests.s3-us-west-1.amazonaws.com:443::::::::: 1
      HTTP 4117: outgoing message end.
      HTTP 4117: SOCKET ERROR: connect ETIMEDOUT 54.231.237.36:443 Error: connect ETIMEDOUT 54.231.237.36:443
          at Object._errnoException (util.js:992:11)
          at _exceptionWithHostPort (util.js:1014:20)
          at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
      node-pre-gyp ERR! install error 
      node-pre-gyp ERR! stack Error: connect ETIMEDOUT 54.231.237.36:443
```

</details>

Next maybe we might want to try some retry logic in the needle GET request?

**Comment by springmeyer** [comment]
quick thoughts (before I review in more detail):

 - are we using the latest needle?
 - any potential bugs in needle that could be compounding (what are the open issues at the needle repo?)
 - `open_timeout: 0` is no timeout - I think we'd be better off matching request default, which is likely the node default of 2 min?
 - I'm surprised we need a custom agent (feels odd). But if we do need it should the `new https.Agent({` be created once per node-pre-gyp or per request (like currently)?

**Comment by mapsam** [comment]
Good questions @springmeyer 

> are we using the latest needle?

Yes 👍 

> any potential bugs in needle that could be compounding

I've done some searching, but all issues related to socket timeouts suggest increasing/removing any combination of the three timeout options.

> I'm surprised we need a custom agent (feels odd)

I'm not suggesting we _need_ one, just testing it out based on some other connection-reliant libraries!

**Comment by mapsam** [comment]
Hm, starting to see socket connection timeouts with `node-pre-gyp publish` commands now. [This build](https://travis-ci.org/mapbox/node-pre-gyp/jobs/393985142#L2411) has the following error:

```
stack RequestTimeout: Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.
```

**Comment by mapsam** [comment]
Interesting update: I went ahead and updated all of the https endpoints for the test apps to **not** include the region-specific endpoint, and am seeing tests pass on the first try, but taking a bit longer ... and then one of the test took 24 minutes and failed with a socket timeout 😢

**Comment by mapsam** [comment]
I'm stumped. Not sure how to prevent these timeouts!

**Comment by springmeyer** [comment]
Have been following the issue queue/comments since the 0.10.1 release (which fixed the needle event handler - https://github.com/mapbox/node-pre-gyp/blob/master/CHANGELOG.md#0101) and there have not been any user reports of `callback never called` or `socket hung up`. So going to close this with the assumption that `callback never called` was fixed by #377 and `socket hung up` was due to network slowness on travis, perhaps?

**Pull request closed without merging**
