### PR TITLE
Support custom binary hosting mirror

### PR DESCRIPTION
**Pull request by fengmk2**
Like we setup a mirror site for node-inspector at
https://npm.taobao.org/mirrors/node-inspector/

These mirrors try to help people download binary files from China.

```bash
$ npm install node-inspector \
  --profiler_binary_host_mirror=https://npm.taobao.org/mirrors/node-inspector/
```

### CODE REVIEW

**Comment by springmeyer** [comment]
I'm hesitant to accept this due to security concerns. So let's work together to brainstorm here if there is a safe way to allow this. My concern is that a malicious application could set this ENV variable (perhaps by writing to ~/.bash_profile) and then a user would unknowingly be installing binaries from a different location.

Possible solutions:

  - add support for shasum validation - this would not completely protect the user but would make it much harder to sneak in malicious binaries
  - require a custom flag be passed to support mirrors like `npm install --allow-binary-mirror`. Only when that flag is passed would the ENV option be respected.
  - use the `npm config` infrastructure instead of an arbitrary ENV option like discussed at https://github.com/mapbox/node-pre-gyp/issues/74

**Comment by fengmk2** [comment]
How about follow npm install config options? 

```bash
$ npm install node-inspector --profiler_binary_host_mirror=http://npm.taobao.org/mirrors/node-inspector/
```

And the `process.env.npm_config_profiler_binary_host_mirror` env it's set by npm.

**Comment by springmeyer** [comment]
Latest fix looks good. Can you think of a good way to test this on travis?

**Comment by fengmk2** [comment]
OK, I try to add test for this change.

**Comment by fengmk2** [comment]
@springmeyer unittest added.

**Comment by fengmk2** [comment]
@springmeyer travis pass now

**Comment by afc163** [comment]
+1

**Comment by fengmk2** [comment]
@springmeyer review again?

**Comment by yiminghe** [comment]
We need this in china :+1:

**Comment by sorrycc** [comment]
+1

**Comment by jsw0528** [comment]
:+1:

**Comment by nightink** [comment]
:+1:

**Comment by fengmk2** [comment]
@springmeyer can you review this again?

**Comment by springmeyer** [comment]
Great, @fengmk2  will merge once you can:

  - [ ] Rebase against latest master and ensure the tests pass
  - [ ] Add docs to the README.md

Sound good? Thanks for this.

**Comment by fengmk2** [comment]
Sure, I will do it today.

**Comment by fengmk2** [comment]
@springmeyer rebase and docs done!

**Comment by springmeyer** [comment]
Thanks @fengmk2!

**Comment by fengmk2** [comment]
Great!

**Pull request merged**
