### PR TITLE
Fix iojs win

### PR DESCRIPTION
**Pull request by springmeyer**
Makes adjustments to the tests to be able to pass with io.js + other refactoring that improves coverage and test consistency.

### CODE REVIEW

**Comment by Mithgol** [comment]
Somehow the changes made in mapbox/node-sqlite3@cdd8d450692224ea83f93264da8053ba251ebdee (they declare 2d72392dc8beff1c59770d9d5c4e1c3f6bf8a271 as the dependency) cannot prevent the message `Module did not self-register` on AppVeyor:

* [platform=x86](https://ci.appveyor.com/project/Mapbox/node-sqlite3/build/1.0.288/job/tpsne7l38yqa7jhf), line 624

* [platform=x64](https://ci.appveyor.com/project/Mapbox/node-sqlite3/build/1.0.288/job/bb65c4fnf9il30w5), line 654

**Comment by springmeyer** [comment]
Those node-pre-gyp fixes only fixed the node-pre-gyp tests - they will have no impact elsewhere. But thanks for trying. So we must have some other problem in node-sqlite3?

**Comment by Mithgol** [comment]
Ah, I've just misunderstood the scope of #148.

If only the tests are fixed, then we should still wait for a fix either in the engine (iojs/io.js#751) or in the building tool (TooTallNate/node-gyp#564); only then the generated modules won't cause that error message.

**Comment by springmeyer** [comment]
Right, or we find a way to call `/path/to/iojs` directly. But I don't currently have good ideas to do that.

**Pull request merged**
