### PR TITLE
chore: run npm audit fix to fix CI

### PR DESCRIPTION
**Pull request by benmccann**

### CODE REVIEW

**Review by cclauss — APPROVED** [review]
Thanks!

**Review by pratikyadav — APPROVED** [review]
Thank you for the fix.

**Comment by pratikyadav** [comment]
👋 @benmccann 
Could you try pushing an empty commit to retrigger Prisma, please?

**Comment by cclauss** [comment]
Thanks @pratikyadav but Prisma still seems to be sleeping.

**Comment by benmccann** [comment]
Done. It's still hanging though

What is that service checking?

This PR is pretty clearly only improving security by addressing the issues that `npm audit` is reporting. Do we need to block on that check?

**Comment by pratikyadav** [comment]
Sorry for the delay caused by this. Let me bring this to the security team. I'll report back as soon as I hear from them.

**Comment by cclauss** [comment]
Nice teamwork here!  Thanks much.

**Pull request merged**
