### PR TITLE
update mkdirp to 1.x

### LINKED ISSUE #495: please remove mkdirp or update it to 1.0.x!
the npm will show vulnerabilities after install node-pre-gyp

### PR DESCRIPTION
**Pull request by felixhao28**
Closes #495

### CODE REVIEW

**Comment by felixhao28** [comment]
Please hold off the merge on this PR until https://github.com/isaacs/node-mkdirp/pull/29 is merged and a new version mkdirp is released.

**Comment by felixhao28** [comment]
2 out of 4 checks still fail, but I don't think they are related to my changes, given that those 2 is already failing on master branch.

**Comment by springmeyer** [comment]
similar fix landed in e67acfa6f4f4cb3b0241286b53d2564c3c56c1fe

**Comment by felixhao28** [comment]
@springmeyer It is your fix compatible with Node 6.x? Currently, mkdirp 1.x is not.

**Comment by springmeyer** [comment]
It is not. node-pre-gyp itself does not attempt to support node v6, only >= v8: https://github.com/mapbox/node-pre-gyp#depends

**Pull request closed without merging**
