### PR TITLE
New branch name

### PR DESCRIPTION
**Pull request by bmacnaughton**
try to get travis tests to run again

### CODE REVIEW

**Comment by bmacnaughton** [comment]
@springmeyer - it probably should be obvious to me, but why aren't the travis tests running on these PRs?

**Comment by springmeyer** [comment]
@bmacnaughton the travis config syntax is likely broken, preventing travis from being able to parse the config and therefore start jobs. You can confirm this by putting it into https://config.travis-ci.com/explore

**Comment by bmacnaughton** [comment]
it looks like the code coverage decrease is because the tests no longer execute the proxy test when the PR is external.

**Comment by bmacnaughton** [comment]
this was for testing; i'll create another based the rebased commits.

**Pull request closed without merging**
