### PR TITLE
upgrade devDependencies

### PR DESCRIPTION
**Pull request by benmccann**
These are simply major version upgrades to keep the library using modern tooling in its testing setup.

This has no effect on consumers of the library since it updates `devDependencies`, which only affects developers of this library (and the CI). Consumers of the library are only affected by changes to the `dependencies` in `package.json`

There were a couple I left out because they would be more complicated and would be better to handle separately. `codecov` has been deprecated and replaced with a GitHub action. The eslint upgrade requires updating the config file, but first the common mapbox config must be updated.

### CODE REVIEW

**Comment by benmccann** [comment]
@lukekarrys could I ask for a quick peek at this one?

**Comment by benmccann** [comment]
@cclauss would you be able to take a look at this PR?

**Comment by lukekarrys** [comment]
Apologies for going MIA on this repo and my responsibilities I promised to take on. My goal is to take a look at everything this weekend, and I have carved on time to do so! 🙌🏼

**Comment by cclauss** [comment]
I know the feeling.  I have the same issues as you on several Python repos.  It is difficult to do the day job and then do this volunteer work.  This is especially true during beautiful summer daze in the gorgeous Swiss Alps!

Thanks massively for your efforts.  I am delighted that you have the skills that I lack and are willing to dedicate some time to getting this project back on track.

**Comment by benmccann** [comment]
Thanks @lukekarrys!

**Comment by benmccann** [comment]
@lukekarrys I thought I'd check back in and see if you might have a chance to lend a pair of eyes to this now?

**Comment by benmccann** [comment]
@lukekarrys just checking in to see if you might be able to lend a pair of eyes on this

**Comment by benmccann** [comment]
The CI is failing on `master` because the CI runs `npm audit`, which is failing. I've sent https://github.com/mapbox/node-pre-gyp/pull/883 to fix that.

I'm not sure it's a good idea to run `npm audit` on the CI because it will make unrelated PRs fail. There are other ways that we can watch to see if there are libraries that need to be updated such as dependabot. What do you guys thing about removing `npm audit` from the CI?

In either case, I really hope we can start getting this backlog of PRs cleared out. Please let me know if there's anything I can do to help

**Comment by cclauss** [comment]
Please rebase

**Review by cclauss — APPROVED** [review]
Nice.  Thanks for your persistence.

**Comment by benmccann** [comment]
No problem. Thanks for the merge!

If you've got time to look at any others, I think that https://github.com/mapbox/node-pre-gyp/pull/875 would probably be the next one to try to get in

**Pull request merged**
