### PR TITLE
add libc detection and {libc} versioning token

### PR DESCRIPTION
**Pull request by core-process**
Improve support for alternate libc libraries, especially `musl` (Alpine), by adding a `{libc}` versioning token. Related to https://github.com/mapbox/node-pre-gyp/issues/325.

Note: A unit test is included (see last test in `test/versioning.test.js`).

### CODE REVIEW

**Comment by core-process** [comment]
See https://github.com/lovell/detect-libc/pull/9

**Comment by core-process** [comment]
@springmeyer requesting review and merge :-)...

**Comment by springmeyer** [comment]
This is incredible work and looks perfect. I will merge now. Will plan to do a release asap.

**Comment by springmeyer** [comment]
released in node-pre-gyp@0.6.39

**Comment by core-process** [comment]
Awesome, thanks! :-)

**Comment by core-process** [comment]
@lovell just fyi: your library is integrated now... :-)

**Comment by rmg** [comment]
This has broken my dockerized app which has none of the binaries in the production image that `detect-libc` uses to infer the libc version :-(

**Comment by springmeyer** [comment]
@rmg thanks for the report - my assumption is that this would be harmless for everyone that did not opt in. Maybe I missed something - what exact error are you seeing?

**Comment by core-process** [comment]
@springmeyer related to https://github.com/lovell/detect-libc/issues/10

**Comment by rmg** [comment]
@core-process thanks for linking it back, I got side-tracked by hunting down the cause. Good news is I found it and there's a pretty trivial workaround I can use on my end.

**Comment by core-process** [comment]
@rmg thanks for your input. Still we want to handle this specific case in detect-libc too. I am glad you found a workaround meanwhile!

**Comment by springmeyer** [comment]
Thanks for the cross link @core-process - I'm still confused however: does anything break if a users is not using the `{libc}` variable? Or is the only issue that trying to get the `{libc}` fails due to lovell/detect-libc#10?

**Comment by core-process** [comment]
@springmeyer `{libc}` resolves to `"unknown"` in this specific case.

**Comment by rmg** [comment]
The actual module I was using was `grpc`, which _does_ use the `{libc}` in its binary name template.

**Comment by core-process** [comment]
@rmg Yes of course it breaks modules which are using this token. @lovell just published the new version of `detect-libc` at npmjs.com and according to our integration test suite your case should work too now. Please let as know if we resolved the issue.

**Comment by rmg** [comment]
I was mostly pointing it out for the benefit of Google :-)

**Pull request merged**
