### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by Emuentes**
NSP check is preventing me from deploying my latest because this module relies on a version of tar-pack that relied on a vulnerable version of tar.

https://nodesecurity.io/advisories/57

### CODE REVIEW

**Comment by Emuentes** [comment]
How do I associate this with an issue?

**Comment by es128** [comment]
Duplicate of #183

**Comment by Emuentes** [comment]
@es128, why does the other pull request not pass all checks for AppVeyor even though they are the same?

**Comment by es128** [comment]
Looks like the tests didn't really run in those cases. Don't know why - appveyor was being flaky or something.

**Comment by springmeyer** [comment]
> @es128, why does the other pull request not pass all checks for AppVeyor even though they are the same?

Looks like some issue with appveyor, rather that the pull. Maybe a network blip. Anyway, thanks both of you for the pull requests. Will merge #183 and tag a new release in the next few minutes.

**Comment by springmeyer** [comment]
closing, as I've merged #183

**Comment by Emuentes** [comment]
Thank you @es128 & @springmeyer for taking care of that!

Have a great week.

**Pull request closed without merging**
