### PR TITLE
feat: add node 15 support

### LINKED ISSUE #517: Update to 15.0.0
Could the `abi_crosswalk.json` file be updated to include 15.0.0 ? It should be something like:
```
  "15.0.0": {
    "node_abi": 84,
    "v8": "8.1"
  }
```

### PR DESCRIPTION
**Pull request by ewanharris**
I ran the `scripts/abi_crosswalk.js` script to update the abi_crosswalk file

Closes #517

### CODE REVIEW

**Comment by piranna** [comment]
There are some errors on CI, can you review them? I'm having problems with `node-pre-gyp` in Node.js 15...

**Comment by ewanharris** [comment]
@piranna The failures on this PR look to be identical to the current state of the master branch. I tested this change with a native module my company uses and the module built fine for me, what issues are you having?

**Comment by piranna** [comment]
> what issues are you having?

With `node-canvas`, after upgrading to Node.js 15 (and by extension, npm 7), it told me that Node.js API versions are incompatible. Rebuild didn't help, so I fully deleted both `node_modules` and `build` directories, and when running `npm install` it fails since it says there's no `node-pre-gyp` executable, and in fact the `node_modules/.bin` folder doesn't exists...

**Comment by ewanharris** [comment]
@piranna, you could try either patching `node_modules/node-pre-gyp/lib/util/abi_crosswalk.json` with the changes you see in this PR to get it building or downgrade Node.js to 14.x until this PR is merged

**Comment by piranna** [comment]
> @piranna, you could try either patching `node_modules/node-pre-gyp/lib/util/abi_crosswalk.json` with the changes you see in this PR to get it building or downgrade Node.js to 14.x until this PR is merged

I'm not in a hurry, I can wait :-)

**Comment by ewanharris** [comment]
Closing as this was done by #520

**Pull request closed without merging**
