### PR TITLE
Update README.md: non bundled dependency tutorial

### PR DESCRIPTION
**Pull request by 3y3**

### CODE REVIEW

**Comment by bminer** [comment]
Why is this not the default approach?  Why is using `bundledDependencies` the recommended configuration?  Seems silly... and a waste of disk space.  node-pre-gyp already weights a whopping 4M, and telling package maintainers to bundle it instead of allowing npm to install it and manage dependencies seems just plain wrong.  Thoughts?

**Comment by bminer** [comment]
+1 for merging

**Comment by 3y3** [comment]
There is opened issue where we discuss about this approach https://github.com/mapbox/node-pre-gyp/issues/162

**Comment by springmeyer** [comment]
difference approach landed in https://github.com/mapbox/node-pre-gyp/pull/201

**Pull request closed without merging**
