### PR TITLE
fix for armv6 / raspberry pi zero

### PR DESCRIPTION
**Pull request by szh**
See https://github.com/mapbox/node-pre-gyp/issues/348#issuecomment-385292205

### CODE REVIEW

**Review by springmeyer — CHANGES_REQUESTED** [review]
@szh thanks for providing this. However there are two blocking things:

 - This will need tests
 - This is backwards incompatible: any existing installs (for binaries already published) will be broken and uninstallable if they upgrade to this. So, you'll need to think through a way to handle this without the risk of breaking existing installs

**Comment by szh** [comment]
I don't have the time to put into this, so you can close this if you want - unless someone else wants to take a crack at it

**Comment by springmeyer** [comment]
okay, will close then, thanks

**Comment by duhruh** [comment]
@springmeyer trying to get caught up on this, as i'm running into issues with this too now. Trying to brainstorm solutions to this, is there any reason we couldn't specifically check for `armv6`  something like

```
 let arch = process.arch
  if (arch === 'arm' && process.config.variables.arm_version === 6) {
    arch = 'armv6l'
  }
```

or would this also break existing binaries? If that's the case then the only other thing I can think of right now would be to put this behind a feature flag something like `process.env.WITH_ARM_VERSION`  I'm willing to propose the PR if you think this is viable.

Thoughts?

**Comment by springmeyer** [comment]
@duhruh I'm pretty sure that would/could break existing installs because that same code is used to resolve already published binaries - so if folks have binaries with just `arm` in them they'd all of a sudden start looking for `armv6l` for previous releases and those would not be found.

> If that's the case then the only other thing I can think of right now would be to put this behind a feature flag something like process.env.WITH_ARM_VERSION I'm willing to propose the PR if you think this is viable.

Yeah, something like that seems required (if a little clumsy). I wonder if the feature flag could be more generic to be more future proof: does this problem exist for other architectures such that the feature flag would not have to be arm specific but rather named something like `WITH_PROCESSOR_VERSIONING` or something?

**Pull request closed without merging**
