### PR TITLE
replace request with request/core

### PR DESCRIPTION
**Pull request by mscdex**
Changing from `request` to `request/core` cuts this module's current total dependency size from 8.8MB to 4.1MB.

### CODE REVIEW

**Comment by mscdex** [comment]
I just saw https://github.com/mapbox/node-pre-gyp/pull/245 after submitting this. I'll keep this here as an alternative to that PR, as this requires less change and probably has better backwards compatibility out of the box.

**Comment by steelbrain** [comment]
Thank you so much for this @mscdex, Just a side note that while this removes the `request` size from 8mb to 4mb, `got` has a size of just 284kb at the time of writing :)

**Comment by mscdex** [comment]
@steelbrain It wasn't `request` itself that was reduced from 8MB to 4MB, it was *this* module's installation footprint.

The current total installation footprint of `@request/core` is ~1.2MB. The current total installation footprint of `got` + `tunnel` (both added in https://github.com/mapbox/node-pre-gyp/pull/245) is ~700KB. So it's not that much of a difference. Like I said, this PR requires less changes and may have better backwards compatibility since it's the *core* part of `request` and `request` is what is being used by this module currently.

**Comment by mscdex** [comment]
@reconbot The total `node_modules` after doing `npm install node-pre-gyp` is what I measured. I used `du -hc node_modules` after installation to get the total counts that I did.

**Comment by springmeyer** [comment]
> my focus is on reducing the total footprint as much as possible.

Thank you @mscdex - Happy to accept further PR's you can think of that further reduce the size.

> Now that I've found the correct numbers. I vote to land this change in 0.6.x!

Agree. This PR feels less risky for basically the same benefit as #245. Will merge now and publish v0.6.32 shortly with this included.

Thanks everyone!

**Comment by springmeyer** [comment]
@mscdex just noticed node v0.10 builds are failing with:

```
$ npm install
-npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'request/core' is not in the npm registry.
```

Is that expected?

**Comment by mscdex** [comment]
@springmeyer I'm guessing the npm that ships with v0.10 doesn't support scopes?

**Comment by springmeyer** [comment]
@mscdex - aha. Can you try changing https://github.com/mapbox/node-pre-gyp/blob/35b10c32926c62817be6a6b91eaa5cadd45f3d5a/.travis.yml#L18 to `NODE_VERSION="0.10" RETIRE=true`? Perhaps the latest `0.10` version brings an npm with scopes support?

**Comment by mscdex** [comment]
@springmeyer Done. It looks like it's passing now.

**Comment by springmeyer** [comment]
Thanks @mscdex - merging now.

**Comment by springmeyer** [comment]
Sorry. It turns out this PR code failed once merged to master. The reason is that [these tests](https://github.com/mapbox/node-pre-gyp/blob/master/test/build.test.js#L312-L386) which cover publishing and installing from the published binaries (this invoked request) were not running in the PR. This is because PR's don't get the `secure` tokens. I need to rework this so that PR's can still test this somehow... but that is a separate issue.

The problem can be seen in https://travis-ci.org/mapbox/node-pre-gyp/jobs/170898126. It looks like each get request using request-core fails now with:

```
stderr: node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: socket hang up
node-pre-gyp ERR! stack     at createHangUpError (_http_client.js:213:15)
node-pre-gyp ERR! stack     at TLSSocket.socketOnEnd (_http_client.js:305:23)
node-pre-gyp ERR! stack     at emitNone (events.js:72:20)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:166:7)
node-pre-gyp ERR! stack     at endReadableNT (_stream_readable.js:921:12)
node-pre-gyp ERR! stack     at nextTickCallbackWith2Args (node.js:442:9)
node-pre-gyp ERR! stack     at process._tickCallback (node.js:356:17)
```

**Comment by springmeyer** [comment]
@mscdex any idea why `socket hang up` is happening? Can you replicate locally, perhaps by testing your PR code with an existing module you can publish (to s3) and then try installing from?

**Comment by mscdex** [comment]
I don't have/use S3, so I don't think I can test that?

**Comment by springmeyer** [comment]
@mscdex - the tests interact with s3 through http so I perhaps the problem can be replicated without s3? If not I'll take a look tomorrow.

**Pull request merged**
